name: Publish to TestFlight

on:
  push:
    paths:
      - 'VERSION'
  pull_request: # Just temporary for testing
    branches: [master]

jobs:
  publish_apps:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn dependencies
        run: yarn

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Install pods
        run: bundle install && yarn pod-install
